"""Changed user model to backref Lxs400 model

Revision ID: 01641984532b
Revises: d70d6003e92c
Create Date: 2021-09-17 13:10:14.290725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01641984532b'
down_revision = 'd70d6003e92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lxs400_vc', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'user', 'lxs400', ['lxs400_vc'], ['verification_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'lxs400_vc')
    # ### end Alembic commands ###
