"""Previous/next question logic

Revision ID: 117127c4f2a1
Revises: 1198dc141174
Create Date: 2021-10-12 18:47:21.355341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117127c4f2a1'
down_revision = '1198dc141174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('next_question', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
