"""Previous question on Question

Revision ID: 1198dc141174
Revises: 554aa275df4c
Create Date: 2021-10-12 18:01:49.517024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1198dc141174'
down_revision = '554aa275df4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('previous_question', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'previous_question')
    # ### end Alembic commands ###
