"""Added has_visited to user

Revision ID: 2c03ec134a23
Revises: 216fcaeec2db
Create Date: 2021-09-27 23:06:51.417259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c03ec134a23'
down_revision = '216fcaeec2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_visited', sa.Boolean(), nullable=True))
    op.alter_column('user', 'rut',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rut',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('user', 'has_visited')
    # ### end Alembic commands ###
