"""Tail

Revision ID: 4b1d08858d67
Revises: a40c2792978d
Create Date: 2021-10-16 01:17:15.999569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1d08858d67'
down_revision = 'a40c2792978d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('tail', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'tail')
    # ### end Alembic commands ###
