"""Added section table

Revision ID: 7c28e33f7bbb
Revises: 7df94b6f95a0
Create Date: 2021-10-12 23:00:42.110357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c28e33f7bbb'
down_revision = '7df94b6f95a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'section_id')
    op.drop_table('section')
    # ### end Alembic commands ###
