"""Added last_question to user

Revision ID: 7df94b6f95a0
Revises: aacdc833171e
Create Date: 2021-10-12 19:50:38.744543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df94b6f95a0'
down_revision = 'aacdc833171e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_question', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_question')
    # ### end Alembic commands ###
