"""empty message

Revision ID: 8f7e7b058160
Revises: 01641984532b
Create Date: 2021-09-17 13:55:47.820975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7e7b058160'
down_revision = '01641984532b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'lxs400', ['lxs400_vc'], ['verification_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
