"""payment

Revision ID: ba0c1b0a646f
Revises: ee8d7197c02f
Create Date: 2021-10-18 02:53:39.211035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0c1b0a646f'
down_revision = 'ee8d7197c02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('rut', sa.String(length=64), nullable=True),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('contact', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    op.drop_table('payment')
    # ### end Alembic commands ###
