"""answer text

Revision ID: ee8d7197c02f
Revises: a8c795e4c1ba
Create Date: 2021-10-17 02:28:47.110401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8d7197c02f'
down_revision = 'a8c795e4c1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('answer_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'answer_text')
    # ### end Alembic commands ###
