"""empty message

Revision ID: ef32f2f6cfbc
Revises: e52d9ca2208c
Create Date: 2021-09-25 21:56:58.554791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef32f2f6cfbc'
down_revision = 'e52d9ca2208c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'lxs400', ['lxs400_vc'], ['verification_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
